apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: xdr-soar
spec:
  serviceName: "influxdb"
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:2.7
