apiVersion: v1
kind: Secret
metadata:
  name: xdr-soar-data-layer
  namespace: xdr-soar
type: Opaque
stringData:
  mongodb-root-username: "${XDR_SOAR_MONGODB_ROOT_USERNAME}"
  mongodb-root-password: "${XDR_SOAR_MONGODB_ROOT_PASSWORD}"
  influxdb-username: "${XDR_SOAR_INFLUXDB_USERNAME}"
  influxdb-password: "${XDR_SOAR_INFLUXDB_PASSWORD}"
  influxdb-org: "${XDR_SOAR_INFLUXDB_ORG}"
  influxdb-bucket: "${XDR_SOAR_INFLUXDB_BUCKET}"
  influxdb-admin-token: "${XDR_SOAR_INFLUXDB_ADMIN_TOKEN}"
  supabase-db-user: "${XDR_SOAR_SUPABASE_DB_USER}"
  supabase-db-password: "${XDR_SOAR_SUPABASE_DB_PASSWORD}"
  supabase-db-name: "${XDR_SOAR_SUPABASE_DB_NAME}"
  supabase-db-url: "${XDR_SOAR_SUPABASE_DB_URL}"
  supabase-db-url-sslmode-disable: "${XDR_SOAR_SUPABASE_DB_URL_SSLMODE_DISABLE}"
  supabase-jwt-secret: "${XDR_SOAR_SUPABASE_JWT_SECRET}"
  supabase-anon-key: "${XDR_SOAR_SUPABASE_ANON_KEY}"
  supabase-service-role-key: "${XDR_SOAR_SUPABASE_SERVICE_ROLE_KEY}"
  supabase-dashboard-username: "${XDR_SOAR_SUPABASE_DASHBOARD_USERNAME}"
  supabase-dashboard-password: "${XDR_SOAR_SUPABASE_DASHBOARD_PASSWORD}"
  grafana-admin-user: "${XDR_SOAR_GRAFANA_ADMIN_USER}"
  grafana-admin-password: "${XDR_SOAR_GRAFANA_ADMIN_PASSWORD}"
  mqtt-username: "${XDR_SOAR_MQTT_USERNAME}"
  mqtt-password: "${XDR_SOAR_MQTT_PASSWORD}"
