apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: xdr-soar
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: xdr-soar
spec:
  clusterIP: None
  ports:
  - name: client
    port: 9092
    targetPort: 9092
  - name: controller
    port: 9093
    targetPort: 9093
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: xdr-soar
spec:
  clusterIP: None
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker
  namespace: xdr-soar
spec:
  ports:
  - name: mqtt
    port: 1883
    targetPort: 1883
  - name: mqtt-tls
    port: 8883
    targetPort: 8883
  selector:
    app: mqtt-broker
---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-broker-external
  namespace: xdr-soar
spec:
  type: ${XDR_SOAR_MQTT_SERVICE_TYPE}
  ports:
  - name: mqtt-tls
    port: 8883
    targetPort: 8883
    nodePort: ${XDR_SOAR_MQTT_NODE_PORT}
  selector:
    app: mqtt-broker
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: xdr-soar
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
