apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-triton-server
  namespace: xdr-soar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-triton
  template:
    metadata:
      labels:
        app: ml-triton
    spec:
      containers:
      - name: triton
        image: nvcr.io/nvidia/tritonserver:latest
        args: ["tritonserver", "--model-repository=/models"]
