apiVersion: apps/v1
kind: Deployment
metadata:
  name: yara-scanner
  namespace: xdr-soar
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yara-scanner
  template:
    metadata:
      labels:
        app: yara-scanner
    spec:
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
      containers:
      - name: yara
        image: custom-yara:latest
