apiVersion: v1
kind: Service
metadata:
  name: ingest-gateway
  namespace: xdr-soar
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: ingest-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: mq-bridge
  namespace: xdr-soar
spec:
  ports:
  - port: 8093
    targetPort: 8093
  selector:
    app: mq-bridge
---
apiVersion: v1
kind: Service
metadata:
  name: stream-processor
  namespace: xdr-soar
spec:
  ports:
  - port: 8094
    targetPort: 8094
  selector:
    app: stream-processor
