apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-broker
  namespace: xdr-soar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-broker
  template:
    metadata:
      labels:
        app: mqtt-broker
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.5.0@sha256:d5703ac4b6cdba024657428661a6334fa4807705286036634ab8ccb73f3e1aef
        volumeMounts:
        - name: mqtt-config
          mountPath: /opt/emqx/etc/base.hocon
          subPath: base.hocon
        - name: mqtt-config
          mountPath: /opt/emqx/etc/auth-built-in-db-bootstrap.csv
          subPath: auth-built-in-db-bootstrap.csv
        - name: mqtt-tls
          mountPath: /opt/emqx/etc/certs
          readOnly: true
        ports:
        - containerPort: 1883
        - containerPort: 8883
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 1883
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: mqtt-config
        configMap:
          name: mqtt-broker-config
      - name: mqtt-tls
        secret:
          secretName: ${XDR_SOAR_MQTT_TLS_SECRET_NAME}
